//发送表单数据
export const SEND_FROM_DATA_REQUEST = 'SEND_FROM_DATA_REQUEST'
export const SEND_FROM_DATA_SUCCESS = 'SEND_FROM_DATA_SUCCESS'
export const SEND_FROM_DATA_FAILURE = 'SEND_FROM_DATA_FAILURE'

//加载表单数据
export const LOAD_FROM_DATA_REQUEST = 'LOAD_FROM_DATA_REQUEST'
export const LOAD_FROM_DATA_SUCCESS = 'LOAD_FROM_DATA_SUCCESS'
export const LOAD_FROM_DATA_FAILURE = 'LOAD_FROM_DATA_FAILURE'