//发送注册用户信息
export const REG_USER_REQUEST = 'REG_USER_REQUEST'
export const REG_USER_SUCCESS = 'REG_USER_SUCCESS'
export const REG_USER_FAILTRUE = 'REG_USER_FAILTRUE'

//登录用户信息
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILTRUE = 'LOGIN_USER_FAILTRUE'


//退出登录
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

//验证登录状态
export const VALIDATION_USER_REQUEST = 'VALIDATION_USER_REQUEST'
export const VALIDATION_USER_SUCCESS = 'VALIDATION_USER_SUCCESS'
export const VALIDATION_USER_FAILURE = 'VALIDATION_USER_FAILURE'